### PR TITLE
EMF profiles fix - Implement node characteristics assignment model

### PR DESCRIPTION
**Pull request by Entenwilli**
This PR creates a node characteristic assignment model. To achieve this, the PR adds the following items
- Implement ecore model for assignments
- Add tree editor support for assignment model

### CODE REVIEW

**Comment by Entenwilli** [comment]
I've implemented the discussed changes and reduced the hierarchy to two layers. The pull request should now be ready for review, but, as discussed, should not be merged until sometime next week. For an example, see the attached screenshot:
meta-model

**Review by sebinside — DISMISSED** [review]
Functionality-wise, everything works as expected. After a quick look of @majuwa, this can be merged from my side.

**Review by majuwa — CHANGES_REQUESTED** [review]
I'm not 100% sure, how the source code is handled. I think @Entenwilli you have not checked it in, but it is also not automatically generated during the build, is it? We probably have two options here, either adding it to the repository or automatically generating it. I would prefer the later one since this is the standard for the PCM metamodel, and we don't have to guess, whether the code in the repository contains manual refinements or not. For this, it is also good, that you have not added it :-) 
For an example of the automatic generation you can look at [this](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/tree/main/releng/org.palladiosimulator.dataflow.dictionary.mwe2) or any other project ending with _.mwe2_ in the [releng](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/tree/main/releng/org.palladiosimulator.dataflow.dictionary.mwe2) folder. We can also discuss it, in more detail at our next meeting.

Another minor point is the generated test bundle. Usually with no custom code it is not required. If we want to keep it, for instance in case of future custom code. I would suggest moving it to the _tests_ folder.

**Comment by Entenwilli** [comment]
I've removed the tests package for the metamodel and added the .mwe2 files for the build. Please look over the changes, especially in the relang folder, I just adapted the configuration from other builds in the directory

**Review by majuwa — APPROVED** [review]
The changes look fine to me

**Review by sebinside — APPROVED** [review]

**Comment by sebinside** [comment]
The meta model is fine, I just encountered that it is possible to get non-fitting values by updating the characteristic type after adding literals: 
image

I would not deal with such inconsistencies in the syntax. However, the analysis might verify that characteristic types and values fit together to prevent careless mistakes by the users.

**Comment by majuwa** [comment]
It might be also possible to modify the editor so that a user cannot select a wrong CharacteristicType. This can be done by extending the edit. @Entenwilli have you written already custom filter operation for the literals? Otherwise, we can discuss these in our next meeting. 
Background: [This](https://github.com/MDSD-Tools/Library-EMFEditUtils) project is helpful in writing a filter operation for the edit project. An example for this can be found in [this project](https://github.com/FluidTrust/Palladio-Addons-ContextConfidentiality-Metamodel/blob/9e0452839b48eca5c08ab3b20aa740e3f7bcd50f/bundles/org.palladiosimulator.pcm.confidentiality.context.edit/src/org/palladiosimulator/pcm/confidentiality/context/system/provider/UsageSpecificationItemProvider.java#L25).

**Comment by majuwa** [comment]
I added a PR #3 for hopefully solving the problem. In the future, we might think about adding a separate feature for the new bundles so that users can install them without installing profiles

**Pull request merged**
